services:
  - type: web
    name: attachment-api
    env: python
    plan: free
    region: oregon
    buildCommand: cd attachment_api && python -m pip install --user -r requirements.txt
    startCommand: cd attachment_api && gunicorn config.wsgi:application --log-file -

