services:
  - type: web
    name: attachment-api
    env: python
    plan: free
    region: oregon
    buildCommand: python3 -m venv /opt/render/project/src/venv && /opt/render/project/src/venv/bin/pip install -r attachment_api/requirements.txt
    startCommand: cd attachment_api && /opt/render/project/src/venv/bin/gunicorn config.wsgi:application --log-file -
